fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc 'Builds project and executes unit tests'
  lane :unit_test do |options|
    scan(
      clean: options[:clean],
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    )
  end

  desc 'Builds and deploys to TestFlight'
  lane :deploy_to_testflight do |options|
    # Ajoutez les étapes nécessaires pour la construction de l'application ici
    gym

    # Envoyer la version à TestFlight
    pilot
  end
end
