name: Pull Request
'on':
  push:
    branches:
      - github-action
  workflow_dispatch: null
jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: '${{ github.token }}'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: ruby/setup-ruby@v1
      - name: Install Bundler
        run: gem install bundler
      - name: Install gems
        run: bundle install
      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: >-
            ${{ runner.os }}-deps-v1-${{
            hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved')
            }}
          restore-keys: '${{ runner.os }}-deps-v1-'
      - name: Decode signing certificate into a file
        env: null
        CERTIFICATE_BASE64: '${{ secrets.IOS_DIST_SIGNING_KEY }}'
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12
      - name: Build & upload iOS binary
        run: bundle exec fastlane ios build_upload_testflight
        env:
          ASC_KEY_ID: '${{ secrets.ASC_KEY_ID }}'
          ASC_ISSUER_ID: '${{ secrets.ASC_ISSUER_ID }}'
          ASC_KEY: '${{ secrets.ASC_PRIVATE_KEY }}'
          SIGNING_KEY_PASSWORD: '${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}'
          SIGNING_KEY_FILE_PATH: signing-cert.p12
      - name: Upload app-store ipa and dsyms to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-store ipa & dsyms
          path: |
            ${{ github.workspace }}/example-iOS.ipa
            ${{ github.workspace }}/*.app.dSYM.zip
